### ISSUE TITLE
Sorting of data in py27 is not working

### ISSUE THREAD

**Issue by me2d09** [stonerlab/Stoner-PythonCode#19]
Following code is not working in Python 2.7 (and also data.sort()...)
```
from Stoner import Data
import numpy as np
data=Data('test2.txt')
np.sort(data.records)
```
Produces: 
> AttributeError: 'list' object has no attribute 'dtype'

I think now it is not a problem with datafile. In Python 3 it is working fine.

[test2.txt](https://github.com/gb119/Stoner-PythonCode/files/2137292/test2.txt)

**Comment by gb119** [comment]
Hmmmm, ok will take a look at this - maybe a couple of days due to a local conference.

**Comment by gb119** [comment]
Sorry, I can't seem to reproduce this problem - above code runs without errors on bath 2.7 and 3.6. It may be that there is some more subtle dependency problem with numpy versions. I'm testing with:

Python 2.7.14 |Anaconda custom (64-bit), numpy 1.14.0, on Linux and Python 2.7.15 |Anaconda, Inc.| (default numpy 1.14.3 on Windows.
